name: The name of your action here
description: Provide a description here
author: Your name or organization here

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  environment:
    description: CI/CD environment
  gitops-repo-suffix:
    description: Suffix for the GitOps repository name
    default: '-gitops'
  gitops-repo:
    description: GitOps repository name (overrides suffix if provided)
  gitops-file-path:
    description: Path to the GitOps file (directory)
    default: 'deploy/environments'
  gitops-file-name:
    description: Name of the GitOps file
    default: 'values.yaml'
  app-name:
    description: Application name
  domain:
    description: Base domain for the service FQDN
    required: true
  dev-url-schema:
    description: URL schema for the dev environment
    default: 'http://'
  dev-port:
    description: Port for the dev environment service
    default: '80'
  version-file:
    description: The version file
    default: version.json

# Define your outputs here.
outputs:
  start-time:
    description: Worflow start time in milliseconds since epoch
  gitops-repo:
    description: The gitops repo name
  effective-branch:
    description:
      The branch to use for GitOps operations (defaults to the head or base
      branch)
  gitops-file:
    description: The gitops file path
  app-name:
    description: The application name
  target-namespace:
    description: The target K8S namespace
  public-service-fqdn:
    description: The public service FQDN
  local-service-fqdn:
    description: The local service FQDN
  service-url:
    description: The service URL
  image-repo:
    description: The image repository
  promoted-version:
    description: The promoted version
  result:
    description: The result of the action

runs:
  using: node20
  main: dist/index.js
