name: The name of your action here
description: Provide a description here
author: Your name or organization here

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  environment:
    description: CI/CD environment
    required: true
    default: 'dev'

# Define your outputs here.
outputs:
  start-time:
    description: Worflow start time in milliseconds since epoch
  gitops-repo:
    description: The gitops repo name
  gitops-file:
    description: The gitops file path
  app-name:
    description: The application name
  target-namespace:
    description: The target K8S namespace
  public-service-fqdn:
    description: The public service FQDN
  local-service-fqdn:
    description: The local service FQDN
  service-url:
    description: The service URL

runs:
  using: node20
  main: dist/index.js
